### ISSUE TITLE
Deleting non heap object

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#6]
https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/4bcddc3882eddd4fc1d603cacc0c8334f3efbaf3/Graph.cpp#L76

You must stop doing this!  You can ONLY delete objects that have been created using `new`

In this case the line can simply be removed.  The stack object will be automatically destroyed when it goes out of scope.

**Comment by C0smicCrush** [comment]
Yea that's why I was getting a segmentation fault. I fixed it this morning though, thanks for letting me know!

**Comment by JamesBremner** [comment]
The error is still there

https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/d68d5a38d8fcf6473d45c140160cad7daae08583/Graph.cpp#L76

**Comment by C0smicCrush** [comment]
Oh my bad I didn't correct the right one. Fixed it now!
